/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface CreateDepositInput {
  'date' : DateText,
  'note' : [] | [string],
  'goalId' : GoalId,
  'amount' : Rupiah,
}
export interface CreateGoalInput {
  'name' : string,
  'photoUrl' : string,
  'targetAmount' : Rupiah,
  'targetDate' : DateText,
  'startDate' : DateText,
}
export interface CreateTrackInput {
  'title' : string,
  'originalFilename' : string,
  'contentType' : string,
  'blob' : ExternalBlob,
  'durationSeconds' : bigint,
  'artist' : string,
  'sizeBytes' : bigint,
}
export type DateText = string;
export type DepositId = bigint;
export interface DepositView {
  'id' : DepositId,
  'date' : DateText,
  'note' : [] | [string],
  'createdAt' : Timestamp,
  'goalId' : GoalId,
  'amount' : Rupiah,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export type GoalId = bigint;
export interface GoalProgress {
  'isReached' : boolean,
  'depositCount' : bigint,
  'goalId' : GoalId,
  'isOverdue' : boolean,
  'remaining' : Rupiah,
  'daysRemaining' : bigint,
  'percentage' : number,
  'totalDeposits' : Rupiah,
}
export interface GoalStats {
  'depositCount' : bigint,
  'goalId' : GoalId,
  'remaining' : Rupiah,
  'averageDeposit' : number,
  'totalDeposits' : Rupiah,
}
export interface GoalView {
  'id' : GoalId,
  'name' : string,
  'createdAt' : Timestamp,
  'photoUrl' : string,
  'targetAmount' : Rupiah,
  'targetDate' : DateText,
  'startDate' : DateText,
}
export interface LastSendResult {
  'message' : string,
  'timestamp' : Timestamp,
  'success' : boolean,
}
export type ReminderError = { 'invalidPhoneNumber' : string } |
  { 'notConfigured' : null } |
  { 'sendFailed' : string } |
  { 'invalidSenderNumber' : string } |
  { 'invalidCredentials' : string };
export interface ReminderSettingsView {
  'apiKeySidSet' : boolean,
  'accountSidMasked' : string,
  'apiKeySidMasked' : string,
  'apiKeySecretSet' : boolean,
  'senderNumber' : string,
  'enabled' : boolean,
  'phoneNumber' : string,
  'accountSidSet' : boolean,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Rupiah = bigint;
export interface SaveReminderSettingsInput {
  'accountSid' : string,
  'senderNumber' : string,
  'apiKeySid' : string,
  'enabled' : boolean,
  'apiKeySecret' : string,
  'phoneNumber' : string,
}
export type SavingsError = { 'invalidInput' : string } |
  { 'goalNotFound' : GoalId } |
  { 'depositNotFound' : DepositId };
export interface SendResult {
  'message' : string,
  'timestamp' : Timestamp,
  'success' : boolean,
}
export type Timestamp = bigint;
export type TrackId = bigint;
export interface TrackView {
  'id' : TrackId,
  'title' : string,
  'originalFilename' : string,
  'contentType' : string,
  'blob' : ExternalBlob,
  'createdAt' : Timestamp,
  'durationSeconds' : bigint,
  'artist' : string,
  'sizeBytes' : bigint,
}
export type TrendPeriod = { 'monthly' : null } |
  { 'daily' : null };
export interface TrendPoint {
  'total' : Rupiah,
  'period' : string,
  'count' : bigint,
}
export interface UpdateDepositInput {
  'id' : DepositId,
  'date' : DateText,
  'note' : [] | [string],
  'amount' : Rupiah,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Add a deposit to one of the caller's savings goals.
   */
  'addDeposit' : ActorMethod<
    [CreateDepositInput],
    { 'ok' : DepositView } |
      { 'err' : SavingsError }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a new savings goal for the caller.
   */
  'createGoal' : ActorMethod<[CreateGoalInput], GoalView>,
  /**
   * / Register an uploaded audio track in the shared library.
   */
  'createTrack' : ActorMethod<[CreateTrackInput], TrackView>,
  /**
   * / Delete an existing deposit owned by the caller.
   */
  'deleteDeposit' : ActorMethod<[bigint], boolean>,
  /**
   * / Delete a savings goal and all of its deposits.
   */
  'deleteGoal' : ActorMethod<[bigint], boolean>,
  /**
   * / Delete an uploaded audio track.
   */
  'deleteTrack' : ActorMethod<[bigint], boolean>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Static Markdown documentation of the backend's public API.
   */
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch a single savings goal owned by the caller.
   */
  'getGoal' : ActorMethod<[bigint], [] | [GoalView]>,
  /**
   * / Read the last reminder send result (admin only).
   */
  'getLastReminderSend' : ActorMethod<[], [] | [LastSendResult]>,
  /**
   * / Compute progress for one of the caller's savings goals.
   */
  'getProgress' : ActorMethod<[bigint, DateText], [] | [GoalProgress]>,
  /**
   * / Read the current reminder settings (admin only). Secrets are masked.
   */
  'getReminderSettings' : ActorMethod<[], ReminderSettingsView>,
  /**
   * / Compute aggregate statistics for one of the caller's savings goals.
   */
  'getStats' : ActorMethod<[bigint], [] | [GoalStats]>,
  /**
   * / Fetch a single uploaded audio track.
   */
  'getTrack' : ActorMethod<[bigint], [] | [TrackView]>,
  /**
   * / Compute the deposit trend for one of the caller's savings goals.
   */
  'getTrend' : ActorMethod<[bigint, TrendPeriod], Array<TrendPoint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Whether the reminder is fully configured (admin only).
   */
  'isReminderConfigured' : ActorMethod<[], boolean>,
  /**
   * / List the deposits of one of the caller's savings goals, newest first.
   */
  'listDeposits' : ActorMethod<[bigint], Array<DepositView>>,
  /**
   * / List every savings goal owned by the caller.
   */
  'listGoals' : ActorMethod<[], Array<GoalView>>,
  /**
   * / List every uploaded audio track, newest first.
   */
  'listTracks' : ActorMethod<[], Array<TrackView>>,
  /**
   * / Save the reminder settings (admin only).
   */
  'saveReminderSettings' : ActorMethod<
    [SaveReminderSettingsInput],
    { 'ok' : ReminderSettingsView } |
      { 'err' : ReminderError }
  >,
  'schema' : ActorMethod<[], string>,
  /**
   * / Send the daily reminder SMS immediately (admin only).
   */
  'sendReminderNow' : ActorMethod<[], SendResult>,
  /**
   * / Update an existing deposit owned by the caller.
   */
  'updateDeposit' : ActorMethod<
    [UpdateDepositInput],
    { 'ok' : DepositView } |
      { 'err' : SavingsError }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];