/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const DateText = IDL.Text;
export const GoalId = IDL.Nat;
export const Rupiah = IDL.Nat;
export const CreateDepositInput = IDL.Record({
  'date' : DateText,
  'note' : IDL.Opt(IDL.Text),
  'goalId' : GoalId,
  'amount' : Rupiah,
});
export const DepositId = IDL.Nat;
export const Timestamp = IDL.Int;
export const DepositView = IDL.Record({
  'id' : DepositId,
  'date' : DateText,
  'note' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'goalId' : GoalId,
  'amount' : Rupiah,
});
export const SavingsError = IDL.Variant({
  'invalidInput' : IDL.Text,
  'goalNotFound' : GoalId,
  'depositNotFound' : DepositId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateGoalInput = IDL.Record({
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'targetAmount' : Rupiah,
  'targetDate' : DateText,
  'startDate' : DateText,
});
export const GoalView = IDL.Record({
  'id' : GoalId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'photoUrl' : IDL.Text,
  'targetAmount' : Rupiah,
  'targetDate' : DateText,
  'startDate' : DateText,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateTrackInput = IDL.Record({
  'title' : IDL.Text,
  'originalFilename' : IDL.Text,
  'contentType' : IDL.Text,
  'blob' : ExternalBlob,
  'durationSeconds' : IDL.Nat,
  'artist' : IDL.Text,
  'sizeBytes' : IDL.Nat,
});
export const TrackId = IDL.Nat;
export const TrackView = IDL.Record({
  'id' : TrackId,
  'title' : IDL.Text,
  'originalFilename' : IDL.Text,
  'contentType' : IDL.Text,
  'blob' : ExternalBlob,
  'createdAt' : Timestamp,
  'durationSeconds' : IDL.Nat,
  'artist' : IDL.Text,
  'sizeBytes' : IDL.Nat,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const LastSendResult = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'success' : IDL.Bool,
});
export const GoalProgress = IDL.Record({
  'isReached' : IDL.Bool,
  'depositCount' : IDL.Nat,
  'goalId' : GoalId,
  'isOverdue' : IDL.Bool,
  'remaining' : Rupiah,
  'daysRemaining' : IDL.Int,
  'percentage' : IDL.Float64,
  'totalDeposits' : Rupiah,
});
export const ReminderSettingsView = IDL.Record({
  'apiKeySidSet' : IDL.Bool,
  'accountSidMasked' : IDL.Text,
  'apiKeySidMasked' : IDL.Text,
  'apiKeySecretSet' : IDL.Bool,
  'senderNumber' : IDL.Text,
  'enabled' : IDL.Bool,
  'phoneNumber' : IDL.Text,
  'accountSidSet' : IDL.Bool,
});
export const GoalStats = IDL.Record({
  'depositCount' : IDL.Nat,
  'goalId' : GoalId,
  'remaining' : Rupiah,
  'averageDeposit' : IDL.Float64,
  'totalDeposits' : Rupiah,
});
export const TrendPeriod = IDL.Variant({
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
});
export const TrendPoint = IDL.Record({
  'total' : Rupiah,
  'period' : IDL.Text,
  'count' : IDL.Nat,
});
export const SaveReminderSettingsInput = IDL.Record({
  'accountSid' : IDL.Text,
  'senderNumber' : IDL.Text,
  'apiKeySid' : IDL.Text,
  'enabled' : IDL.Bool,
  'apiKeySecret' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const ReminderError = IDL.Variant({
  'invalidPhoneNumber' : IDL.Text,
  'notConfigured' : IDL.Null,
  'sendFailed' : IDL.Text,
  'invalidSenderNumber' : IDL.Text,
  'invalidCredentials' : IDL.Text,
});
export const SendResult = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'success' : IDL.Bool,
});
export const UpdateDepositInput = IDL.Record({
  'id' : DepositId,
  'date' : DateText,
  'note' : IDL.Opt(IDL.Text),
  'amount' : Rupiah,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addDeposit' : IDL.Func(
      [CreateDepositInput],
      [IDL.Variant({ 'ok' : DepositView, 'err' : SavingsError })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGoal' : IDL.Func([CreateGoalInput], [GoalView], []),
  'createTrack' : IDL.Func([CreateTrackInput], [TrackView], []),
  'deleteDeposit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGoal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTrack' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGoal' : IDL.Func([IDL.Nat], [IDL.Opt(GoalView)], ['query']),
  'getLastReminderSend' : IDL.Func([], [IDL.Opt(LastSendResult)], ['query']),
  'getProgress' : IDL.Func(
      [IDL.Nat, DateText],
      [IDL.Opt(GoalProgress)],
      ['query'],
    ),
  'getReminderSettings' : IDL.Func([], [ReminderSettingsView], ['query']),
  'getStats' : IDL.Func([IDL.Nat], [IDL.Opt(GoalStats)], ['query']),
  'getTrack' : IDL.Func([IDL.Nat], [IDL.Opt(TrackView)], ['query']),
  'getTrend' : IDL.Func(
      [IDL.Nat, TrendPeriod],
      [IDL.Vec(TrendPoint)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isReminderConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listDeposits' : IDL.Func([IDL.Nat], [IDL.Vec(DepositView)], ['query']),
  'listGoals' : IDL.Func([], [IDL.Vec(GoalView)], ['query']),
  'listTracks' : IDL.Func([], [IDL.Vec(TrackView)], ['query']),
  'saveReminderSettings' : IDL.Func(
      [SaveReminderSettingsInput],
      [IDL.Variant({ 'ok' : ReminderSettingsView, 'err' : ReminderError })],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'sendReminderNow' : IDL.Func([], [SendResult], []),
  'updateDeposit' : IDL.Func(
      [UpdateDepositInput],
      [IDL.Variant({ 'ok' : DepositView, 'err' : SavingsError })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const DateText = IDL.Text;
  const GoalId = IDL.Nat;
  const Rupiah = IDL.Nat;
  const CreateDepositInput = IDL.Record({
    'date' : DateText,
    'note' : IDL.Opt(IDL.Text),
    'goalId' : GoalId,
    'amount' : Rupiah,
  });
  const DepositId = IDL.Nat;
  const Timestamp = IDL.Int;
  const DepositView = IDL.Record({
    'id' : DepositId,
    'date' : DateText,
    'note' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'goalId' : GoalId,
    'amount' : Rupiah,
  });
  const SavingsError = IDL.Variant({
    'invalidInput' : IDL.Text,
    'goalNotFound' : GoalId,
    'depositNotFound' : DepositId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateGoalInput = IDL.Record({
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'targetAmount' : Rupiah,
    'targetDate' : DateText,
    'startDate' : DateText,
  });
  const GoalView = IDL.Record({
    'id' : GoalId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'photoUrl' : IDL.Text,
    'targetAmount' : Rupiah,
    'targetDate' : DateText,
    'startDate' : DateText,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateTrackInput = IDL.Record({
    'title' : IDL.Text,
    'originalFilename' : IDL.Text,
    'contentType' : IDL.Text,
    'blob' : ExternalBlob,
    'durationSeconds' : IDL.Nat,
    'artist' : IDL.Text,
    'sizeBytes' : IDL.Nat,
  });
  const TrackId = IDL.Nat;
  const TrackView = IDL.Record({
    'id' : TrackId,
    'title' : IDL.Text,
    'originalFilename' : IDL.Text,
    'contentType' : IDL.Text,
    'blob' : ExternalBlob,
    'createdAt' : Timestamp,
    'durationSeconds' : IDL.Nat,
    'artist' : IDL.Text,
    'sizeBytes' : IDL.Nat,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const LastSendResult = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'success' : IDL.Bool,
  });
  const GoalProgress = IDL.Record({
    'isReached' : IDL.Bool,
    'depositCount' : IDL.Nat,
    'goalId' : GoalId,
    'isOverdue' : IDL.Bool,
    'remaining' : Rupiah,
    'daysRemaining' : IDL.Int,
    'percentage' : IDL.Float64,
    'totalDeposits' : Rupiah,
  });
  const ReminderSettingsView = IDL.Record({
    'apiKeySidSet' : IDL.Bool,
    'accountSidMasked' : IDL.Text,
    'apiKeySidMasked' : IDL.Text,
    'apiKeySecretSet' : IDL.Bool,
    'senderNumber' : IDL.Text,
    'enabled' : IDL.Bool,
    'phoneNumber' : IDL.Text,
    'accountSidSet' : IDL.Bool,
  });
  const GoalStats = IDL.Record({
    'depositCount' : IDL.Nat,
    'goalId' : GoalId,
    'remaining' : Rupiah,
    'averageDeposit' : IDL.Float64,
    'totalDeposits' : Rupiah,
  });
  const TrendPeriod = IDL.Variant({ 'monthly' : IDL.Null, 'daily' : IDL.Null });
  const TrendPoint = IDL.Record({
    'total' : Rupiah,
    'period' : IDL.Text,
    'count' : IDL.Nat,
  });
  const SaveReminderSettingsInput = IDL.Record({
    'accountSid' : IDL.Text,
    'senderNumber' : IDL.Text,
    'apiKeySid' : IDL.Text,
    'enabled' : IDL.Bool,
    'apiKeySecret' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const ReminderError = IDL.Variant({
    'invalidPhoneNumber' : IDL.Text,
    'notConfigured' : IDL.Null,
    'sendFailed' : IDL.Text,
    'invalidSenderNumber' : IDL.Text,
    'invalidCredentials' : IDL.Text,
  });
  const SendResult = IDL.Record({
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'success' : IDL.Bool,
  });
  const UpdateDepositInput = IDL.Record({
    'id' : DepositId,
    'date' : DateText,
    'note' : IDL.Opt(IDL.Text),
    'amount' : Rupiah,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addDeposit' : IDL.Func(
        [CreateDepositInput],
        [IDL.Variant({ 'ok' : DepositView, 'err' : SavingsError })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGoal' : IDL.Func([CreateGoalInput], [GoalView], []),
    'createTrack' : IDL.Func([CreateTrackInput], [TrackView], []),
    'deleteDeposit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGoal' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTrack' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGoal' : IDL.Func([IDL.Nat], [IDL.Opt(GoalView)], ['query']),
    'getLastReminderSend' : IDL.Func([], [IDL.Opt(LastSendResult)], ['query']),
    'getProgress' : IDL.Func(
        [IDL.Nat, DateText],
        [IDL.Opt(GoalProgress)],
        ['query'],
      ),
    'getReminderSettings' : IDL.Func([], [ReminderSettingsView], ['query']),
    'getStats' : IDL.Func([IDL.Nat], [IDL.Opt(GoalStats)], ['query']),
    'getTrack' : IDL.Func([IDL.Nat], [IDL.Opt(TrackView)], ['query']),
    'getTrend' : IDL.Func(
        [IDL.Nat, TrendPeriod],
        [IDL.Vec(TrendPoint)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isReminderConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listDeposits' : IDL.Func([IDL.Nat], [IDL.Vec(DepositView)], ['query']),
    'listGoals' : IDL.Func([], [IDL.Vec(GoalView)], ['query']),
    'listTracks' : IDL.Func([], [IDL.Vec(TrackView)], ['query']),
    'saveReminderSettings' : IDL.Func(
        [SaveReminderSettingsInput],
        [IDL.Variant({ 'ok' : ReminderSettingsView, 'err' : ReminderError })],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'sendReminderNow' : IDL.Func([], [SendResult], []),
    'updateDeposit' : IDL.Func(
        [UpdateDepositInput],
        [IDL.Variant({ 'ok' : DepositView, 'err' : SavingsError })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };