/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export interface CreateDepositInput {
    date: DateText;
    note?: string;
    goalId: GoalId;
    amount: Rupiah;
}
export interface CreateGoalInput {
    name: string;
    photoUrl: string;
    targetAmount: Rupiah;
    targetDate: DateText;
    startDate: DateText;
}
export interface CreateTrackInput {
    title: string;
    originalFilename: string;
    contentType: string;
    blob: ExternalBlob;
    durationSeconds: bigint;
    artist: string;
    sizeBytes: bigint;
}
export type DateText = string;
export type DepositId = bigint;
export interface DepositView {
    id: DepositId;
    date: DateText;
    note?: string;
    createdAt: Timestamp;
    goalId: GoalId;
    amount: Rupiah;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export type GoalId = bigint;
export interface GoalProgress {
    isReached: boolean;
    depositCount: bigint;
    goalId: GoalId;
    isOverdue: boolean;
    remaining: Rupiah;
    daysRemaining: bigint;
    percentage: number;
    totalDeposits: Rupiah;
}
export interface GoalStats {
    depositCount: bigint;
    goalId: GoalId;
    remaining: Rupiah;
    averageDeposit: number;
    totalDeposits: Rupiah;
}
export interface GoalView {
    id: GoalId;
    name: string;
    createdAt: Timestamp;
    photoUrl: string;
    targetAmount: Rupiah;
    targetDate: DateText;
    startDate: DateText;
}
export interface LastSendResult {
    message: string;
    timestamp: Timestamp;
    success: boolean;
}
export type ReminderError = {
    __kind__: "invalidPhoneNumber";
    invalidPhoneNumber: string;
} | {
    __kind__: "notConfigured";
    notConfigured: null;
} | {
    __kind__: "sendFailed";
    sendFailed: string;
} | {
    __kind__: "invalidSenderNumber";
    invalidSenderNumber: string;
} | {
    __kind__: "invalidCredentials";
    invalidCredentials: string;
};
export interface ReminderSettingsView {
    apiKeySidSet: boolean;
    accountSidMasked: string;
    apiKeySidMasked: string;
    apiKeySecretSet: boolean;
    senderNumber: string;
    enabled: boolean;
    phoneNumber: string;
    accountSidSet: boolean;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Rupiah = bigint;
export interface SaveReminderSettingsInput {
    accountSid: string;
    senderNumber: string;
    apiKeySid: string;
    enabled: boolean;
    apiKeySecret: string;
    phoneNumber: string;
}
export type SavingsError = {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "goalNotFound";
    goalNotFound: GoalId;
} | {
    __kind__: "depositNotFound";
    depositNotFound: DepositId;
};
export interface SendResult {
    message: string;
    timestamp: Timestamp;
    success: boolean;
}
export type Timestamp = bigint;
export type TrackId = bigint;
export interface TrackView {
    id: TrackId;
    title: string;
    originalFilename: string;
    contentType: string;
    blob: ExternalBlob;
    createdAt: Timestamp;
    durationSeconds: bigint;
    artist: string;
    sizeBytes: bigint;
}
export interface TrendPoint {
    total: Rupiah;
    period: string;
    count: bigint;
}
export interface UpdateDepositInput {
    id: DepositId;
    date: DateText;
    note?: string;
    amount: Rupiah;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum TrendPeriod {
    monthly = "monthly",
    daily = "daily"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Add a deposit to one of the caller's savings goals.
     */
    addDeposit(input: CreateDepositInput): Promise<{
        __kind__: "ok";
        ok: DepositView;
    } | {
        __kind__: "err";
        err: SavingsError;
    }>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Create a new savings goal for the caller.
     */
    createGoal(input: CreateGoalInput): Promise<GoalView>;
    /**
     * / Register an uploaded audio track in the shared library.
     */
    createTrack(input: CreateTrackInput): Promise<TrackView>;
    /**
     * / Delete an existing deposit owned by the caller.
     */
    deleteDeposit(id: bigint): Promise<boolean>;
    /**
     * / Delete a savings goal and all of its deposits.
     */
    deleteGoal(id: bigint): Promise<boolean>;
    /**
     * / Delete an uploaded audio track.
     */
    deleteTrack(id: bigint): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Static Markdown documentation of the backend's public API.
     */
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Fetch a single savings goal owned by the caller.
     */
    getGoal(id: bigint): Promise<GoalView | null>;
    /**
     * / Read the last reminder send result (admin only).
     */
    getLastReminderSend(): Promise<LastSendResult | null>;
    /**
     * / Compute progress for one of the caller's savings goals.
     */
    getProgress(goalId: bigint, today: DateText): Promise<GoalProgress | null>;
    /**
     * / Read the current reminder settings (admin only). Secrets are masked.
     */
    getReminderSettings(): Promise<ReminderSettingsView>;
    /**
     * / Compute aggregate statistics for one of the caller's savings goals.
     */
    getStats(goalId: bigint): Promise<GoalStats | null>;
    /**
     * / Fetch a single uploaded audio track.
     */
    getTrack(id: bigint): Promise<TrackView | null>;
    /**
     * / Compute the deposit trend for one of the caller's savings goals.
     */
    getTrend(goalId: bigint, period: TrendPeriod): Promise<Array<TrendPoint>>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Whether the reminder is fully configured (admin only).
     */
    isReminderConfigured(): Promise<boolean>;
    /**
     * / List the deposits of one of the caller's savings goals, newest first.
     */
    listDeposits(goalId: bigint): Promise<Array<DepositView>>;
    /**
     * / List every savings goal owned by the caller.
     */
    listGoals(): Promise<Array<GoalView>>;
    /**
     * / List every uploaded audio track, newest first.
     */
    listTracks(): Promise<Array<TrackView>>;
    /**
     * / Save the reminder settings (admin only).
     */
    saveReminderSettings(input: SaveReminderSettingsInput): Promise<{
        __kind__: "ok";
        ok: ReminderSettingsView;
    } | {
        __kind__: "err";
        err: ReminderError;
    }>;
    schema(): Promise<string>;
    /**
     * / Send the daily reminder SMS immediately (admin only).
     */
    sendReminderNow(): Promise<SendResult>;
    /**
     * / Update an existing deposit owned by the caller.
     */
    updateDeposit(input: UpdateDepositInput): Promise<{
        __kind__: "ok";
        ok: DepositView;
    } | {
        __kind__: "err";
        err: SavingsError;
    }>;
}
import type { Cell as _Cell, CreateDepositInput as _CreateDepositInput, CreateTrackInput as _CreateTrackInput, DateText as _DateText, DepositId as _DepositId, DepositView as _DepositView, Error as _Error, ExternalBlob as _ExternalBlob, GoalId as _GoalId, GoalProgress as _GoalProgress, GoalStats as _GoalStats, GoalView as _GoalView, LastSendResult as _LastSendResult, ReminderError as _ReminderError, ReminderSettingsView as _ReminderSettingsView, Result as _Result, Result__1 as _Result__1, Rupiah as _Rupiah, SavingsError as _SavingsError, Timestamp as _Timestamp, TrackId as _TrackId, TrackView as _TrackView, TrendPeriod as _TrendPeriod, UpdateDepositInput as _UpdateDepositInput, UserRole as _UserRole, Value as _Value, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addDeposit(arg0: CreateDepositInput): Promise<{
        __kind__: "ok";
        ok: DepositView;
    } | {
        __kind__: "err";
        err: SavingsError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addDeposit(to_candid_CreateDepositInput_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDeposit(to_candid_CreateDepositInput_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createGoal(arg0: CreateGoalInput): Promise<GoalView> {
        if (this.processError) {
            try {
                const result = await this.actor.createGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGoal(arg0);
            return result;
        }
    }
    async createTrack(arg0: CreateTrackInput): Promise<TrackView> {
        if (this.processError) {
            try {
                const result = await this.actor.createTrack(await to_candid_CreateTrackInput_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TrackView_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTrack(await to_candid_CreateTrackInput_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TrackView_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDeposit(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDeposit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDeposit(arg0);
            return result;
        }
    }
    async deleteGoal(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0);
            return result;
        }
    }
    async deleteTrack(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTrack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTrack(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoal(arg0: bigint): Promise<GoalView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoal(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoal(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLastReminderSend(): Promise<LastSendResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastReminderSend();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastReminderSend();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProgress(arg0: bigint, arg1: DateText): Promise<GoalProgress | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgress(arg0, arg1);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgress(arg0, arg1);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReminderSettings(): Promise<ReminderSettingsView> {
        if (this.processError) {
            try {
                const result = await this.actor.getReminderSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReminderSettings();
            return result;
        }
    }
    async getStats(arg0: bigint): Promise<GoalStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrack(arg0: bigint): Promise<TrackView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrack(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrack(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTrend(arg0: bigint, arg1: TrendPeriod): Promise<Array<TrendPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTrend(arg0, to_candid_TrendPeriod_n41(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTrend(arg0, to_candid_TrendPeriod_n41(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isReminderConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isReminderConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isReminderConfigured();
            return result;
        }
    }
    async listDeposits(arg0: bigint): Promise<Array<DepositView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDeposits(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDeposits(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listGoals(): Promise<Array<GoalView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGoals();
            return result;
        }
    }
    async listTracks(): Promise<Array<TrackView>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTracks();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTracks();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveReminderSettings(arg0: SaveReminderSettingsInput): Promise<{
        __kind__: "ok";
        ok: ReminderSettingsView;
    } | {
        __kind__: "err";
        err: ReminderError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReminderSettings(arg0);
                return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReminderSettings(arg0);
            return from_candid_variant_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async sendReminderNow(): Promise<SendResult> {
        if (this.processError) {
            try {
                const result = await this.actor.sendReminderNow();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendReminderNow();
            return result;
        }
    }
    async updateDeposit(arg0: UpdateDepositInput): Promise<{
        __kind__: "ok";
        ok: DepositView;
    } | {
        __kind__: "err";
        err: SavingsError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeposit(to_candid_UpdateDepositInput_n47(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeposit(to_candid_UpdateDepositInput_n47(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Cell_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_DepositView_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositView): DepositView {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ReminderError_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReminderError): ReminderError {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_SavingsError_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SavingsError): SavingsError {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_TrackView_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TrackView): Promise<TrackView> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GoalView]): GoalView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LastSendResult]): LastSendResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GoalProgress]): GoalProgress | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GoalStats]): GoalStats | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TrackView]): Promise<TrackView | null> {
    return value.length === 0 ? null : await from_candid_TrackView_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DepositId;
    date: _DateText;
    note: [] | [string];
    createdAt: _Timestamp;
    goalId: _GoalId;
    amount: _Rupiah;
}): {
    id: DepositId;
    date: DateText;
    note?: string;
    createdAt: Timestamp;
    goalId: GoalId;
    amount: Rupiah;
} {
    return {
        id: value.id,
        date: value.date,
        note: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.note)),
        createdAt: value.createdAt,
        goalId: value.goalId,
        amount: value.amount
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TrackId;
    title: string;
    originalFilename: string;
    contentType: string;
    blob: _ExternalBlob;
    createdAt: _Timestamp;
    durationSeconds: bigint;
    artist: string;
    sizeBytes: bigint;
}): Promise<{
    id: TrackId;
    title: string;
    originalFilename: string;
    contentType: string;
    blob: ExternalBlob;
    createdAt: Timestamp;
    durationSeconds: bigint;
    artist: string;
    sizeBytes: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        originalFilename: value.originalFilename,
        contentType: value.contentType,
        blob: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.blob),
        createdAt: value.createdAt,
        durationSeconds: value.durationSeconds,
        artist: value.artist,
        sizeBytes: value.sizeBytes
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n29(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n33(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _DepositView;
} | {
    err: _SavingsError;
}): {
    __kind__: "ok";
    ok: DepositView;
} | {
    __kind__: "err";
    err: SavingsError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_DepositView_n15(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_SavingsError_n18(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidInput: string;
} | {
    goalNotFound: _GoalId;
} | {
    depositNotFound: _DepositId;
}): {
    __kind__: "invalidInput";
    invalidInput: string;
} | {
    __kind__: "goalNotFound";
    goalNotFound: GoalId;
} | {
    __kind__: "depositNotFound";
    depositNotFound: DepositId;
} {
    return "invalidInput" in value ? {
        __kind__: "invalidInput",
        invalidInput: value.invalidInput
    } : "goalNotFound" in value ? {
        __kind__: "goalNotFound",
        goalNotFound: value.goalNotFound
    } : "depositNotFound" in value ? {
        __kind__: "depositNotFound",
        depositNotFound: value.depositNotFound
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ReminderSettingsView;
} | {
    err: _ReminderError;
}): {
    __kind__: "ok";
    ok: ReminderSettingsView;
} | {
    __kind__: "err";
    err: ReminderError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_ReminderError_n45(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invalidPhoneNumber: string;
} | {
    notConfigured: null;
} | {
    sendFailed: string;
} | {
    invalidSenderNumber: string;
} | {
    invalidCredentials: string;
}): {
    __kind__: "invalidPhoneNumber";
    invalidPhoneNumber: string;
} | {
    __kind__: "notConfigured";
    notConfigured: null;
} | {
    __kind__: "sendFailed";
    sendFailed: string;
} | {
    __kind__: "invalidSenderNumber";
    invalidSenderNumber: string;
} | {
    __kind__: "invalidCredentials";
    invalidCredentials: string;
} {
    return "invalidPhoneNumber" in value ? {
        __kind__: "invalidPhoneNumber",
        invalidPhoneNumber: value.invalidPhoneNumber
    } : "notConfigured" in value ? {
        __kind__: "notConfigured",
        notConfigured: value.notConfigured
    } : "sendFailed" in value ? {
        __kind__: "sendFailed",
        sendFailed: value.sendFailed
    } : "invalidSenderNumber" in value ? {
        __kind__: "invalidSenderNumber",
        invalidSenderNumber: value.invalidSenderNumber
    } : "invalidCredentials" in value ? {
        __kind__: "invalidCredentials",
        invalidCredentials: value.invalidCredentials
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DepositView>): Array<DepositView> {
    return value.map((x)=>from_candid_DepositView_n15(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TrackView>): Promise<Array<TrackView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TrackView_n24(_uploadFile, _downloadFile, x)));
}
function to_candid_CreateDepositInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateDepositInput): _CreateDepositInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_CreateTrackInput_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateTrackInput): Promise<_CreateTrackInput> {
    return await to_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_TrendPeriod_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TrendPeriod): _TrendPeriod {
    return value == TrendPeriod.monthly ? {
        monthly: null
    } : value == TrendPeriod.daily ? {
        daily: null
    } : value;
}
function to_candid_UpdateDepositInput_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateDepositInput): _UpdateDepositInput {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: DateText;
    note?: string;
    goalId: GoalId;
    amount: Rupiah;
}): {
    date: _DateText;
    note: [] | [string];
    goalId: _GoalId;
    amount: _Rupiah;
} {
    return {
        date: value.date,
        note: value.note ? candid_some(value.note) : candid_none(),
        goalId: value.goalId,
        amount: value.amount
    };
}
async function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    originalFilename: string;
    contentType: string;
    blob: ExternalBlob;
    durationSeconds: bigint;
    artist: string;
    sizeBytes: bigint;
}): Promise<{
    title: string;
    originalFilename: string;
    contentType: string;
    blob: _ExternalBlob;
    durationSeconds: bigint;
    artist: string;
    sizeBytes: bigint;
}> {
    return {
        title: value.title,
        originalFilename: value.originalFilename,
        contentType: value.contentType,
        blob: await to_candid_ExternalBlob_n23(_uploadFile, _downloadFile, value.blob),
        durationSeconds: value.durationSeconds,
        artist: value.artist,
        sizeBytes: value.sizeBytes
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: DepositId;
    date: DateText;
    note?: string;
    amount: Rupiah;
}): {
    id: _DepositId;
    date: _DateText;
    note: [] | [string];
    amount: _Rupiah;
} {
    return {
        id: value.id,
        date: value.date,
        note: value.note ? candid_some(value.note) : candid_none(),
        amount: value.amount
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
